name: Build CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 22 * * *'  # every day at 22:00 UTC

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-20
          override: true
          components: rust-src, rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Check code format
        run: cargo fmt --all -- --check
      - name: Clippy LibOS
        run: cargo clippy --all-features
      - name: Clippy x86_64 bare-metal
        run: cd zCore && make clippy ARCH=x86_64
      - name: Clippy riscv64 bare-metal
        run: cd zCore && make clippy ARCH=riscv64 LINUX=1

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-20
          components: rust-src, llvm-tools-preview
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
      - uses: Swatinem/rust-cache@v1
      - name: Build all packages
        run: cargo build
      - name: Build linux LibOS
        run: cargo build --package zcore --features "linux libos"
      - name: Build zircon LibOS
        run: cargo build --package zcore --features "zircon libos"
      - name: Build x86_64 bare-metal
        run: cd zCore && make build ARCH=x86_64
      - name: Build riscv64 bare-metal
        run: cd zCore && make build ARCH=riscv64 LINUX=1

  build-aarch64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-20
          override: true
          target: aarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --target aarch64-unknown-linux-gnu --workspace --exclude linux-syscall --exclude zcore-loader --exclude zcore

  build-user:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-20
          target: x86_64-fuchsia
      - name: Build Zircon user programs
        run: cd zircon-user && make build MODE=release

  build-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docs
        run: cargo doc --no-deps --all-features

  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        arch: [libos, x86_64, riscv64]
        mode: [linux, zircon]
        command: [clippy, build]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ matrix.command }}
        run: echo "done"
